server:
  port: 8888

spring:
<<<<<<< HEAD
  application:
    name: config
=======
>>>>>>> origin/creacion-micro-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srdejo/config
