server:
  port: 8091

logging:
  level:
    org:
      springframework: ERROR

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        jdbc: 
          lob: 
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin