server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:srdejo/ecosistema-ms-spring-cloud.git
          default-label: master
          searchPaths: config-enviroment